#!/usr/bin/env python
import yaml
import io
import requests
from time import sleep
import subprocess


URL = 'https://drive.google.com/uc?export=download&id=1dXMOhuP6DtztbZ4FxfJzFQAB-mKs2Gzk'
response = requests.get(URL)
settings_yaml = response.content.decode('ascii')

settings = yaml.safe_load(settings_yaml)
print(settings["stream"])


return_code = subprocess.call(['mplayer', settings["stream"]])
print("Output of call() : ", return_code)

